# Generated by Django 5.1.4 on 2026-07-11 20:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('powered', models.BooleanField(default=True, help_text='Motorised equipment needs a ramp pass and TUV.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='ops.department')),
                ('user', models.OneToOneField(blank=True, help_text='Optional login account for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('registration_number', models.CharField(blank=True, max_length=40)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('MAINTENANCE', 'Maintenance'), ('PM_DUE', 'PM Due'), ('TUV_EXPIRED', 'TUV Expired'), ('RAMP_PASS_EXPIRED', 'Ramp Pass Expired'), ('OOS', 'OOS'), ('SCRAP', 'Scrap')], db_index=True, default='AVAILABLE', max_length=20)),
                ('pm_due_date', models.DateField(blank=True, null=True, verbose_name='PM due date')),
                ('tuv_expiry_date', models.DateField(blank=True, null=True, verbose_name='TUV expiry')),
                ('ramp_pass_expiry_date', models.DateField(blank=True, null=True, verbose_name='Ramp pass expiry')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Insurance expiry')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/photos/')),
                ('remarks', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='ops.department')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='ops.equipmenttype')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('TUV', 'TUV Certificate'), ('RAMP_PASS', 'Ramp Pass'), ('INSURANCE', 'Insurance'), ('REGISTRATION', 'Registration'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='equipment/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ops.equipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(help_text='IATA station code, e.g. DXB', max_length=10)),
                ('area', models.CharField(blank=True, max_length=60)),
                ('zone', models.CharField(blank=True, max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='ops.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_locations', to='ops.employee', verbose_name='Responsible supervisor')),
            ],
            options={
                'ordering': ['station', 'name'],
                'unique_together': {('station', 'name')},
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_here', to='ops.location', verbose_name='Current location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_employees', to='ops.location'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('ALLOCATE', 'Allocate'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return')], max_length=10)),
                ('allocation_date', models.DateField(default=datetime.date.today)),
                ('allocation_time', models.TimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_raised', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_approved', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ops.equipment')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='ops.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='ops.location')),
            ],
            options={
                'ordering': ['-allocation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('validity_months', models.PositiveIntegerField(default=24, help_text='How long a pass stays valid.')),
                ('equipment_types', models.ManyToManyField(blank=True, help_text='Equipment types this certification licenses an employee to operate.', related_name='required_courses', to='ops.equipmenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training/certificates/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ops.trainingcourse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='ops.employee')),
            ],
            options={
                'ordering': ['-completed_on'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('serviceable', models.PositiveIntegerField(default=0)),
                ('readiness_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.location')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('snapshot_date', 'location')},
            },
        ),
    ]
