# Generated by Django 5.1.4 on 2026-07-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='customer_site_access',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_class',
            field=models.CharField(blank=True, max_length=40, verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_owner',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fleet_number',
            field=models.CharField(blank=True, db_index=True, help_text="The customer's equipment number for this same unit.", max_length=40, null=True, unique=True, verbose_name='Fleet number'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_overage',
            field=models.BooleanField(db_index=True, default=False, help_text='Past its nominal service life but still counted in the fleet.', verbose_name='Overage unit'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('STATION', 'Station Equipment'), ('LOCAL_SUPPORT', 'From Local Station to Support'), ('SRA', 'Station Equipment - SRA'), ('OUT_STATION', 'Sent to Support Out-Station')], db_index=True, default='STATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_number',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Equipment number (GS)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Blank means the unit has never been assigned a parking location.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_here', to='ops.location', verbose_name='Current location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=80, verbose_name='OEM model'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Receipt date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='OEM serial number'),
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(blank=True, default='Ramp', max_length=40)),
                ('reason', models.CharField(choices=[('REPAIR', 'Repair'), ('PM', 'PM'), ('TUV', 'TUV'), ('RS', 'R/S (Gate 3 security case)')], db_index=True, max_length=10)),
                ('start_date', models.DateField(db_index=True)),
                ('closed_on', models.DateField(blank=True, db_index=True, help_text='Blank while still out.', null=True)),
                ('service_request_number', models.CharField(blank=True, max_length=30, verbose_name='Service request #')),
                ('workshop_location', models.CharField(blank=True, help_text='Workshop, Gate 3, a stand, etc.', max_length=60)),
                ('work_order_request_time', models.CharField(blank=True, help_text='24h, as recorded on the sheet (e.g. 0732)', max_length=10)),
                ('time_sent_to_workshop', models.CharField(blank=True, max_length=40)),
                ('status_note', models.CharField(blank=True, max_length=120)),
                ('gse_group_remarks', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_events', to='ops.equipment')),
            ],
            options={
                'ordering': ['-start_date', 'equipment__equipment_number'],
                'indexes': [models.Index(fields=['closed_on', 'reason'], name='ops_service_closed__d6eb07_idx')],
            },
        ),
    ]
